<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="42" ignored="0" total="46" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Logo" duration-ms="114240" started-at="2019-09-06T12:01:22Z" finished-at="2019-09-06T12:03:17Z">
    <groups>
    </groups>
    <test name="Logo" duration-ms="114240" started-at="2019-09-06T12:01:22Z" finished-at="2019-09-06T12:03:17Z">
      <class name="Logo">
        <test-method status="PASS" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3092" started-at="2019-09-06T12:01:23Z" data-provider="data" finished-at="2019-09-06T12:01:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[efectycolombia]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payvalida/Efecty, folder=Efecty, shortcode=efectycolombia, called_name=efecty}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3270" started-at="2019-09-06T12:01:26Z" data-provider="data" finished-at="2019-09-06T12:01:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[pse]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payvalida/PSE, folder=PSE, shortcode=pse, called_name=pse}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2356" started-at="2019-09-06T12:01:30Z" data-provider="data" finished-at="2019-09-06T12:01:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[boletobancario]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx, folder=Boleto, shortcode=boletobancario, called_name=boleto}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="PASS" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2459" started-at="2019-09-06T12:01:32Z" data-provider="data" finished-at="2019-09-06T12:01:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[santandermexico]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Astropay/Santander Mexico, folder=Santander, shortcode=santandermexico, called_name=santander}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2151" started-at="2019-09-06T12:01:35Z" data-provider="data" finished-at="2019-09-06T12:01:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[oxxo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Astropay/OXXO, folder=OXXO, shortcode=oxxo, called_name=oxxo}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3199" started-at="2019-09-06T12:01:37Z" data-provider="data" finished-at="2019-09-06T12:01:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ccbrazil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx CC, folder=Ebanx\\Ebanx (Visa,Mastercard only), shortcode=ccbrazil, called_name=ebanx}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NamedWrong] expected [name] but found [ps-ebanx-d@2x],
[NamedWrong] expected [name] but found [ps-ebanx-@2x],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NamedWrong] expected [name] but found [ps-ebanx-d@2x],
[NamedWrong] expected [name] but found [ps-ebanx-@2x],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2343" started-at="2019-09-06T12:01:40Z" data-provider="data" finished-at="2019-09-06T12:01:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ccbrazilhipercard]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx CC Hipercard, folder=Hiperbank, shortcode=ccbrazilhipercard, called_name=hipercard}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1920" started-at="2019-09-06T12:01:42Z" data-provider="data" finished-at="2019-09-06T12:01:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[itaubrazil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx/Banco Itau, folder=Itau, shortcode=itaubrazil, called_name=itau}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1946" started-at="2019-09-06T12:01:44Z" data-provider="data" finished-at="2019-09-06T12:01:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[bancobrazil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx/Banco do Brazil, folder=Banco do Brazil, shortcode=bancobrazil, called_name=bancodobrazil}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2052" started-at="2019-09-06T12:01:46Z" data-provider="data" finished-at="2019-09-06T12:01:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[banrisulbrazil]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Ebanx/Banco Banrisul, folder=Banrisul, shortcode=banrisulbrazil, called_name=banrisul}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NamedWrong] expected [name] but found [ps-banrisul-d@2x],
[NamedWrong] expected [name] but found [ps-banrisul-@2x],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NamedWrong] expected [name] but found [ps-banrisul-d@2x],
[NamedWrong] expected [name] but found [ps-banrisul-@2x],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="PASS" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2108" started-at="2019-09-06T12:01:48Z" data-provider="data" finished-at="2019-09-06T12:01:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[efecty]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Astropay/Efecty, folder=Efecty, shortcode=efecty, called_name=efecty}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3068" started-at="2019-09-06T12:01:50Z" data-provider="data" finished-at="2019-09-06T12:01:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpaymt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/mTransfer, folder=mBank, shortcode=dotpaymt, called_name=mbank}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3268" started-at="2019-09-06T12:01:53Z" data-provider="data" finished-at="2019-09-06T12:01:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpaybzwbk]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/Bank Zachodni WBK, folder=WBK, shortcode=dotpaybzwbk, called_name=wbk}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3334" started-at="2019-09-06T12:01:57Z" data-provider="data" finished-at="2019-09-06T12:02:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpayingb]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/ING Bank Slaski, folder=ING, shortcode=dotpayingb, called_name=ing}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3537" started-at="2019-09-06T12:02:00Z" data-provider="data" finished-at="2019-09-06T12:02:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpayinteligo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/Inteligo, folder=Inteligo, shortcode=dotpayinteligo, called_name=inteligo}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3381" started-at="2019-09-06T12:02:04Z" data-provider="data" finished-at="2019-09-06T12:02:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dotpayingbacc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Dotpay/Place z ING Bank Slaski, folder=Dotpay Place z ING Bank Slaski, shortcode=dotpayingbacc, called_name=dotpay ing bank slaski}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3168" started-at="2019-09-06T12:02:07Z" data-provider="data" finished-at="2019-09-06T12:02:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[happyvoucher]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/Happy Voucher, folder=Happyvoucher, shortcode=happyvoucher, called_name=happyvoucher}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2116" started-at="2019-09-06T12:02:10Z" data-provider="data" finished-at="2019-09-06T12:02:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[teencash]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/TeenCash, folder=Teencash, shortcode=teencash, called_name=teencash}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1820" started-at="2019-09-06T12:02:12Z" data-provider="data" finished-at="2019-09-06T12:02:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[oncash]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/OnCash, folder=Oncash, shortcode=oncash, called_name=oncash}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1945" started-at="2019-09-06T12:02:14Z" data-provider="data" finished-at="2019-09-06T12:02:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[eggmoney]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/Eggmoney, folder=Eggmoney, shortcode=eggmoney, called_name=eggmoney}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2785" started-at="2019-09-06T12:02:16Z" data-provider="data" finished-at="2019-09-06T12:02:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[culturevoucher]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/Culture Voucher, folder=Culture voucher, shortcode=culturevoucher, called_name=culture voucher}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NamedWrong] expected [name] but found [culture voucher_original],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NamedWrong] expected [name] but found [culture voucher_original],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3353" started-at="2019-09-06T12:02:19Z" data-provider="data" finished-at="2019-09-06T12:02:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[allthegate]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/AllTheGate CC, folder=Payletter AlltheGate, shortcode=allthegate, called_name=payletterallthegate}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NamedWrong] expected [name] but found [pm-psallthegate-merchantareav5],
[NamedWrong] expected [name] but found [pm-ps-alltregate (noflag)],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NamedWrong] expected [name] but found [pm-psallthegate-merchantareav5],
[NamedWrong] expected [name] but found [pm-ps-alltregate (noflag)],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3008" started-at="2019-09-06T12:02:22Z" data-provider="data" finished-at="2019-09-06T12:02:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[bookculture]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Payletter/Book Gift Voucher, folder=BookGiftVoucher, shortcode=bookculture, called_name=bookgiftvoucher}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NamedWrong] expected [name] but found [book voucher v5],
[NamedWrong] expected [name] but found [book voucher v7],
[NamedWrong] expected [name] but found [book voucher_original],
[multi][Height] expected [43] but found [44],
[NotEnoughDesign] expected [isMissing] but found [uni]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NamedWrong] expected [name] but found [book voucher v5],
[NamedWrong] expected [name] but found [book voucher v7],
[NamedWrong] expected [name] but found [book voucher_original],
[multi][Height] expected [43] but found [44],
[NotEnoughDesign] expected [isMissing] but found [uni]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2029" started-at="2019-09-06T12:02:25Z" data-provider="data" finished-at="2019-09-06T12:02:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[idealpayments]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=PPRO/iDeal, folder=PPRO IDEAL, shortcode=idealpayments, called_name=ppro ideal}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3376" started-at="2019-09-06T12:02:27Z" data-provider="data" finished-at="2019-09-06T12:02:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[gameon]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Game-ON, folder=Game On, shortcode=gameon, called_name=game-on}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[ImageNotReplaced] expected [] but found [dark2],
[ImageNotReplaced] expected [] but found [dark3],
[ImageNotReplaced] expected [] but found [dark],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3057" started-at="2019-09-06T12:02:31Z" data-provider="data" finished-at="2019-09-06T12:02:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[culturevoucherkr]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Culture Voucher, folder=Culture land, shortcode=culturevoucherkr, called_name=culture land}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NamedWrong] expected [name] but found [_ps-culture-land-@2x],
[NamedWrong] expected [name] but found [ps-culture-land-d@3x],
[NamedWrong] expected [name] but found [ps-culture-land],
[NamedWrong] expected [name] but found [ps-culture-land-@3x],
[NamedWrong] expected [name] but found [ps-culture-land-d],
[NamedWrong] expected [name] but found [_ps-culture-land-d@2x],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NamedWrong] expected [name] but found [_ps-culture-land-@2x],
[NamedWrong] expected [name] but found [ps-culture-land-d@3x],
[NamedWrong] expected [name] but found [ps-culture-land],
[NamedWrong] expected [name] but found [ps-culture-land-@3x],
[NamedWrong] expected [name] but found [ps-culture-land-d],
[NamedWrong] expected [name] but found [_ps-culture-land-d@2x],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="3091" started-at="2019-09-06T12:02:34Z" data-provider="data" finished-at="2019-09-06T12:02:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[teencashkr]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Teencash, folder=Teencash, shortcode=teencashkr, called_name=teencash}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2329" started-at="2019-09-06T12:02:37Z" data-provider="data" finished-at="2019-09-06T12:02:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[banktransfercn]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Umpay bank transfer, folder=Umpay, shortcode=banktransfercn, called_name=umpay}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2020" started-at="2019-09-06T12:02:39Z" data-provider="data" finished-at="2019-09-06T12:02:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[boletobr]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=MercadoPago/Boleto, folder=Boleto, shortcode=boletobr, called_name=boleto}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2023" started-at="2019-09-06T12:02:41Z" data-provider="data" finished-at="2019-09-06T12:02:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[idealnl]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Mollie/Ideal, folder=Ideal, shortcode=idealnl, called_name=ideal}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2031" started-at="2019-09-06T12:02:43Z" data-provider="data" finished-at="2019-09-06T12:02:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[yandexmoney]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Yandex Money, folder=Yandex, shortcode=yandexmoney, called_name=yandex}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2107" started-at="2019-09-06T12:02:45Z" data-provider="data" finished-at="2019-09-06T12:02:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[sberbankonline]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Sberbank Online, folder=Sberbank, shortcode=sberbankonline, called_name=sberbank}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2040" started-at="2019-09-06T12:02:47Z" data-provider="data" finished-at="2019-09-06T12:02:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[alfaclickya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Alfa Click, folder=AlfaBank, shortcode=alfaclickya, called_name=alfabank}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="PASS" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2168" started-at="2019-09-06T12:02:49Z" data-provider="data" finished-at="2019-09-06T12:02:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[tinkoff]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Tinkoff, folder=Tinkoff, shortcode=tinkoff, called_name=tinkoff}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2192" started-at="2019-09-06T12:02:51Z" data-provider="data" finished-at="2019-09-06T12:02:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[yacash]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Yandex/Cash, folder=YandexCash, shortcode=yacash, called_name=yandexcash}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2060" started-at="2019-09-06T12:02:54Z" data-provider="data" finished-at="2019-09-06T12:02:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[walmart]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Openbucks/Walmart, folder=Walmart moneygram, shortcode=walmart, called_name=walmartmoneygram}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1967" started-at="2019-09-06T12:02:56Z" data-provider="data" finished-at="2019-09-06T12:02:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[moneygram]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Openbucks/MoneyGram, folder=Moneygram, shortcode=moneygram, called_name=moneygram}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1856" started-at="2019-09-06T12:02:58Z" data-provider="data" finished-at="2019-09-06T12:03:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[canadapost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Openbucks/Canada Post, folder=Canadapost, shortcode=canadapost, called_name=canadapost}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NamedWrong] expected [name] but found [ps-canada-post-d],
[NamedWrong] expected [name] but found [ps-canada-post],
[NamedWrong] expected [name] but found [pm-ps-canada-big],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NamedWrong] expected [name] but found [ps-canada-post-d],
[NamedWrong] expected [name] but found [ps-canada-post],
[NamedWrong] expected [name] but found [pm-ps-canada-big],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2773" started-at="2019-09-06T12:03:00Z" data-provider="data" finished-at="2019-09-06T12:03:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[banktransferth]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Megapay / Bank transfer Thailand, folder=, shortcode=banktransferth, called_name=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2117" started-at="2019-09-06T12:03:02Z" data-provider="data" finished-at="2019-09-06T12:03:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[gateway]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Gateway, folder=Gateway, shortcode=gateway, called_name=Gateway}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1803" started-at="2019-09-06T12:03:04Z" data-provider="data" finished-at="2019-09-06T12:03:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[gateway]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Gateway - AMEX only, folder=AMEX, shortcode=gateway, called_name=AMEX}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NamedWrong] expected [name] but found [_ps-amex-@2x],
[NamedWrong] expected [name] but found [ps-amex-d],
[NamedWrong] expected [name] but found [pm-psamex-merchantareav5],
[NamedWrong] expected [name] but found [ps-amex-d@3x],
[NamedWrong] expected [name] but found [pm-ps-amex],
[NamedWrong] expected [name] but found [ps-amex],
[NamedWrong] expected [name] but found [_ps-amex-d@2x],
[NamedWrong] expected [name] but found [pm-psamex-big],
[NamedWrong] expected [name] but found [ps-amex-@3x],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NamedWrong] expected [name] but found [_ps-amex-@2x],
[NamedWrong] expected [name] but found [ps-amex-d],
[NamedWrong] expected [name] but found [pm-psamex-merchantareav5],
[NamedWrong] expected [name] but found [ps-amex-d@3x],
[NamedWrong] expected [name] but found [pm-ps-amex],
[NamedWrong] expected [name] but found [ps-amex],
[NamedWrong] expected [name] but found [_ps-amex-d@2x],
[NamedWrong] expected [name] but found [pm-psamex-big],
[NamedWrong] expected [name] but found [ps-amex-@3x],
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1850" started-at="2019-09-06T12:03:06Z" data-provider="data" finished-at="2019-09-06T12:03:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[epspayments]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=PPRO/EPS, folder=, shortcode=epspayments, called_name=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1841" started-at="2019-09-06T12:03:08Z" data-provider="data" finished-at="2019-09-06T12:03:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mol]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=zGold-MOLPoints, folder=, shortcode=mol, called_name=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="1786" started-at="2019-09-06T12:03:10Z" data-provider="data" finished-at="2019-09-06T12:03:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[multibanco]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=PPRO/Multibanco, folder=, shortcode=multibanco, called_name=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2764" started-at="2019-09-06T12:03:12Z" data-provider="data" finished-at="2019-09-06T12:03:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[epinpaymentsystem]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=MINT, folder=, shortcode=epinpaymentsystem, called_name=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[ImageNotReplaced] expected [] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[ImageNotReplaced] expected [] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[ImageNotReplaced] expected [] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[ImageNotReplaced] expected [] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2],
[ImageNotReplaced] expected [] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
        <test-method status="FAIL" signature="getLogoFile(java.lang.String, java.util.Map)[pri:0, instance:Logo@57baeedf]" name="getLogoFile" duration-ms="2148" started-at="2019-09-06T12:03:15Z" data-provider="data" finished-at="2019-09-06T12:03:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[cvspharmacy]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[{psname=Openbucks/CVS Pharmacy, folder=, shortcode=cvspharmacy, called_name=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[NotEnoughDesign] expected [isMissing] but found [uni],
[NotEnoughDesign] expected [isMissing] but found [dark2],
[NotEnoughDesign] expected [isMissing] but found [dark3],
[NotEnoughDesign] expected [isMissing] but found [light],
[NotEnoughDesign] expected [isMissing] but found [dark],
[NotEnoughDesign] expected [isMissing] but found [light3],
[NotEnoughDesign] expected [isMissing] but found [multi],
[NotEnoughDesign] expected [isMissing] but found [v5],
[NotEnoughDesign] expected [isMissing] but found [light2]
at automation.project3ds.Assertion.end(Assertion.java:26)
at Logo.getLogoFile(Logo.java:225)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogoFile -->
      </class> <!-- Logo -->
    </test> <!-- Logo -->
  </suite> <!-- Logo -->
</testng-results>
