<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="testBrickURL" duration-ms="79789" started-at="2019-07-19T07:46:45Z" finished-at="2019-07-19T07:48:04Z">
    <groups>
    </groups>
    <test name="testBrickURL" duration-ms="79789" started-at="2019-07-19T07:46:45Z" finished-at="2019-07-19T07:48:04Z">
      <class name="automation.project3ds.testBrickURL">
        <test-method status="FAIL" signature="execute(java.lang.String, java.lang.String, java.util.Map)[pri:0, instance:automation.project3ds.testBrickURL@5bcab519]" name="execute" duration-ms="72163" started-at="2019-07-19T07:46:51Z" data-provider="data" finished-at="2019-07-19T07:48:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4000000000001000]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://feature-pwg-1108.wallapi.bamboo.stuffio.com/brick/test-staging/brick-custom.html]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[{Cavv=value, cardholderVerificationMethod=THREEDS, expected_results_authentication=NA, Enrolled=Y, EciFlag=05, WhiteListStatus=null, ErrorDesc=blank, WhiteListStatusSource=null, ErrorNo=0, Payload=blank, PAN=4000000000001000, SignitureVerification=Y, ACSUrl=blank, PAResStatus=Y, testName=Test Visa 1: Successful Frictionless Authentication}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[Enrolled] expected [Y] but found [U],
[PAResStatus] expected [Y] but found [null],
[SignitureVerification] expected [Y] but found [null],
[Cavv] expected object to not be null,
[EciFlag] expected [05] but found [07],
[cardholderVerificationMethod3] expected [THREEDS] but found [CVV2],
[cavv] expected object to not be null,
[version] expected [V2] but found [null],
[directoryServerTransactionId] expected object to not be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[Enrolled] expected [Y] but found [U],
[PAResStatus] expected [Y] but found [null],
[SignitureVerification] expected [Y] but found [null],
[Cavv] expected object to not be null,
[EciFlag] expected [05] but found [07],
[cardholderVerificationMethod3] expected [THREEDS] but found [CVV2],
[cavv] expected object to not be null,
[version] expected [V2] but found [null],
[directoryServerTransactionId] expected object to not be null
at automation.project3ds.MySoftAssertAll.assertAll(MySoftAssertAll.java:57)
at automation.project3ds.testBrickURL.execute(testBrickURL.java:315)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- execute -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:automation.project3ds.testBrickURL@5bcab519]" name="tearDown" is-config="true" duration-ms="731" started-at="2019-07-19T07:48:04Z" finished-at="2019-07-19T07:48:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automation.project3ds.testBrickURL -->
    </test> <!-- testBrickURL -->
  </suite> <!-- testBrickURL -->
</testng-results>
