<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="628" started-at="2019-07-19T09:33:44Z" finished-at="2019-07-19T09:33:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="628" started-at="2019-07-19T09:33:44Z" finished-at="2019-07-19T09:33:45Z">
      <class name="automation.project3ds.Aa">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:automation.project3ds.Aa@146ba0ac]" name="setUp" is-config="true" duration-ms="41" started-at="2019-07-19T09:33:44Z" finished-at="2019-07-19T09:33:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[url]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="meo(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:automation.project3ds.Aa@146ba0ac]" name="meo" duration-ms="471" started-at="2019-07-19T09:33:44Z" data-provider="data" finished-at="2019-07-19T09:33:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[param1Value]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[url]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[param2Value]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[MESSAGE] expected [0] but found [1],
[MESSAGE] expected not [meo] to but still found [meo],
[MESSAGE] expected not [null] to but still found [null],
[MESSAGE] expected [null] but found [meo],
[MESSAGE] expected [null] but found [meo],
[MESSAGE] expected object to not be null,
[MESSAGE] expected [gau] but found [meo]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[MESSAGE] expected [0] but found [1],
[MESSAGE] expected not [meo] to but still found [meo],
[MESSAGE] expected not [null] to but still found [null],
[MESSAGE] expected [null] but found [meo],
[MESSAGE] expected [null] but found [meo],
[MESSAGE] expected object to not be null,
[MESSAGE] expected [gau] but found [meo]
at automation.project3ds.MySoftAssertAll.assertAll(MySoftAssertAll.java:57)
at automation.project3ds.Aa.meo(Aa.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- meo -->
        <test-method status="FAIL" signature="meo(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:automation.project3ds.Aa@146ba0ac]" name="meo" duration-ms="82" started-at="2019-07-19T09:33:45Z" data-provider="data" finished-at="2019-07-19T09:33:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[param1Value]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[url]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[param2Value]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
[MESSAGE] expected [0] but found [1],
[MESSAGE] expected not [meo] to but still found [meo],
[MESSAGE] expected not [null] to but still found [null],
[MESSAGE] expected [null] but found [meo],
[MESSAGE] expected [null] but found [meo],
[MESSAGE] expected object to not be null,
[MESSAGE] expected [gau] but found [meo]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
[MESSAGE] expected [0] but found [1],
[MESSAGE] expected not [meo] to but still found [meo],
[MESSAGE] expected not [null] to but still found [null],
[MESSAGE] expected [null] but found [meo],
[MESSAGE] expected [null] but found [meo],
[MESSAGE] expected object to not be null,
[MESSAGE] expected [gau] but found [meo]
at automation.project3ds.MySoftAssertAll.assertAll(MySoftAssertAll.java:57)
at automation.project3ds.Aa.meo(Aa.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- meo -->
      </class> <!-- automation.project3ds.Aa -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
